artifact_uri: /Users/fauzanghaza/Documents/[03]Organization/[02]ICN/[03]Member/[04]Prototype/[01]Water_Potability_Detection/water-potability-ml-service/Modelling/mlflow.fauzanghaza.com/152430416136368919/9b07d0e3200b455490f5e9c5393f9ded/artifacts
end_time: 1731180769303
entry_point_name: ''
experiment_id: '152430416136368919'
lifecycle_stage: active
run_id: 9b07d0e3200b455490f5e9c5393f9ded
run_name: abundant-turtle-305
run_uuid: 9b07d0e3200b455490f5e9c5393f9ded
source_name: ''
source_type: 4
source_version: ''
start_time: 1731180767398
status: 3
tags: []
user_id: fauzanghaza
