services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service
    ports:
      - "50051:50051"
    environment:
      MLFLOW_TRACKING_USERNAME: ${MLFLOW_ADMIN_USERNAME}
      MLFLOW_TRACKING_PASSWORD: ${MLFLOW_ADMIN_PASSWORD}
      MLFLOW_TRACKING_URI: ${MLFLOW_URL}
      MLFLOW_S3_IGNORE_TLS: "true"
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "pgrep", "-f", "server.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - water-potability

networks:
  water-potability:
    name: water-potability

