# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: water_potability.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'water_potability.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16water_potability.proto\x12\x10water_potability\"g\n\x1dPredictWaterPotabilityRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\n\n\x02ph\x18\x02 \x01(\x01\x12\x1b\n\x13totalDissolveSolids\x18\x03 \x01(\x01\x12\x11\n\tturbidity\x18\x04 \x01(\x01\"k\n\x1ePredictWaterPotabilityResponse\x12\x12\n\nprediction\x18\x01 \x01(\x01\x12\r\n\x05level\x18\x02 \x01(\t\x12&\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x17.water_potability.Error\"&\n\x05\x45rror\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t2\x95\x01\n\x16WaterPotabilityService\x12{\n\x16PredictWaterPotability\x12/.water_potability.PredictWaterPotabilityRequest\x1a\x30.water_potability.PredictWaterPotabilityResponseB,Z*./internal/water_potability/handler/rpc/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'water_potability_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*./internal/water_potability/handler/rpc/pb'
  _globals['_PREDICTWATERPOTABILITYREQUEST']._serialized_start=44
  _globals['_PREDICTWATERPOTABILITYREQUEST']._serialized_end=147
  _globals['_PREDICTWATERPOTABILITYRESPONSE']._serialized_start=149
  _globals['_PREDICTWATERPOTABILITYRESPONSE']._serialized_end=256
  _globals['_ERROR']._serialized_start=258
  _globals['_ERROR']._serialized_end=296
  _globals['_WATERPOTABILITYSERVICE']._serialized_start=299
  _globals['_WATERPOTABILITYSERVICE']._serialized_end=448
# @@protoc_insertion_point(module_scope)
